import { rootFolder } from '#utils/constants';
import { LogLevel } from '@sapphire/framework';
import { setup } from '@skyra/env-utilities';
import { type ClientOptions, IntentsBitField, Options } from 'discord.js';
import { join } from 'node:path';

setup(join(rootFolder, 'src', '.env'));

const { Flags } = IntentsBitField;

export const CLIENT_OPTIONS: ClientOptions = {
	disableMentionPrefix: false,
	defaultPrefix: ';',
	intents: [Flags.GuildMessages, Flags.MessageContent, Flags.Guilds, Flags.GuildMembers],
	makeCache: Options.cacheEverything(),
	loadDefaultErrorListeners: process.env.NODE_ENV !== 'production',
	logger: { level: process.env.NODE_ENV === 'production' ? LogLevel.Info : LogLevel.Debug },
	loadMessageCommandListeners: true,
	allowedMentions: { users: ['624320717571227658'], roles: [] },
	subcommandsAdvanced: { nameCommandsAutogenerated: true }
};
